name: celer-env
dependencies:
  - python>=3.8
  - pip
  # dependencies
  - Cython>=0.26
  - matplotlib>=2.0.0
  - numpy>=1.12
  - scikit-learn>=0.23
  - scipy>=0.18.0
  - seaborn>=0.7
  - tqdm
  - xarray
  - pip:
    - download
    - libsvmdata
  # dev dependencies
  - pytest
  - flake8
